apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APPLICATION_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${APPLICATION_NAME}
  template:
    metadata:
      labels:
        app: ${APPLICATION_NAME}
    spec:
      containers:
        - name: ${APPLICATION_NAME}
          image: ${CONTAINER_IMAGE_TAGGED}
          resources:
            requests:
              memory: "128Mi"
              cpu: "10m"
            limits:
              memory: "256Mi"
              cpu: "600m"
          ports:
            - containerPort: 80
          env:
            - name: DATABASE_URL
              value: ${DATABASE_URL}
            - name: NUXT_PUBLIC_DEVELOPER
              value: Leah Ishiguro
            - name: NUXT_PUBLIC_DEVELOPER_HOMEPAGE
              value: https://gitlab.jtektrnd.net/leahishiguro
            - name: NUXT_APP_REPO
              value: https://gitlab.jtektrnd.net/eks/moreillon/skill_map_back
            - name: NUXT_OAUTH_OIDC_OPENID_CONFIG
              value: https://keycloak.jtektrnd.net/realms/jtekt/.well-known/openid-configuration
            - name: NUXT_OAUTH_OIDC_CLIENT_ID
              value: public
            - name: NUXT_SESSION_PASSWORD
              value: ${NUXT_SESSION_PASSWORD}
            - name: NUXT_PUBLIC_USER_LOOKUP_URL
              value: https://employees-api.jtektrnd.net/v3/users
            - name: NUXT_PUBLIC_USER_LOOKUP_IDENTIFIER_FIELD
              value: username
            - name: NUXT_PUBLIC_USER_LOOKUP_DISPLAY_NAME_FIELD
              value: display_name
      imagePullSecrets:
        - name: ${K8S_ECR_SECRET_NAME}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${APPLICATION_NAME}
spec:
  ingressClassName: jtektrnd-net
  rules:
    - host: ${APPLICATION_NAME}.jtektrnd.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ${APPLICATION_NAME}
                port:
                  number: 80

---
---
apiVersion: v1
kind: Service
metadata:
  name: ${APPLICATION_NAME}
spec:
  ports:
    - port: 80
  selector:
    app: ${APPLICATION_NAME}
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APPLICATION_NAME}-redirection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${APPLICATION_NAME}-redirection
  template:
    metadata:
      labels:
        app: ${APPLICATION_NAME}-redirection
    spec:
      containers:
        - name: ${APPLICATION_NAME}-redirection
          image: moreillon/redirection:c8ab3fdf
          env:
            - name: REDIRECTION_TARGET_URL
              value: https://skill-map.jtektrnd.net
            - name: REDIRECTION_WARN
              value: "true"

---
apiVersion: v1
kind: Service
metadata:
  name: ${APPLICATION_NAME}-redirection
spec:
  type: NodePort
  selector:
    app: ${APPLICATION_NAME}-redirection
  ports:
    - port: 80
      nodePort: ${K8S_SERVICE_PORT}
