apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APPLICATION_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${APPLICATION_NAME}
  template:
    metadata:
      labels:
        app: ${APPLICATION_NAME}
    spec:
      containers:
        - name: ${APPLICATION_NAME}
          image: ${CONTAINER_IMAGE_TAGGED}
          ports:
            - containerPort: 80
          env:
            - name: DATABASE_URL
              value: ${DATABASE_URL}
            - name: NUXT_PUBLIC_USER_MANAGER_API_URL
              value: https://employees-api.jtektrnd.net
            - name: NUXT_PUBLIC_DEVELOPER
              value: Leah Ishiguro
            - name: NUXT_PUBLIC_DEVELOPER_HOMEPAGE
              value: https://gitlab.jtektrnd.net/leahishiguro
            - name: NUXT_APP_REPO
              value: https://gitlab.jtektrnd.net/eks/moreillon/skill_map_back
            - name: NUXT_OIDC_PROVIDERS_KEYCLOAK_CLIENT_ID
              value: public
            - name: NUXT_OIDC_PROVIDERS_KEYCLOAK_AUTHORIZATION_URL
              value: https://keycloak.jtektrnd.net/realms/jtekt/protocol/openid-connect/auth
            - name: NUXT_OIDC_PROVIDERS_KEYCLOAK_TOKEN_URL
              value: https://keycloak.jtektrnd.net/realms/jtekt/protocol/openid-connect/token
            - name: NUXT_OIDC_PROVIDERS_KEYCLOAK_USER_INFO_URL
              value: https://keycloak.jtektrnd.net/realms/jtekt/protocol/openid-connect/userinfo
            - name: NUXT_OIDC_PROVIDERS_KEYCLOAK_LOGOUT_URL
              value: https://keycloak.jtektrnd.net/realms/jtekt/protocol/openid-connect/logout
            - name: NUXT_OIDC_PROVIDERS_KEYCLOAK_BASE_URL
              value: https://keycloak.jtektrnd.net/realms/jtekt
            - name: NUXT_OIDC_PROVIDERS_KEYCLOAK_REDIRECT_URI
              value: https://skill-map.jtektrnd.net/auth/keycloak/callback
            - name: NUXT_OIDC_PROVIDERS_KEYCLOAK_LOGOUT_REDIRECT_URI
              value: https://skill-map.jtektrnd.net
      imagePullSecrets:
        - name: ${K8S_ECR_SECRET_NAME}
---
apiVersion: v1
kind: Service
metadata:
  name: ${APPLICATION_NAME}
spec:
  type: NodePort
  selector:
    app: ${APPLICATION_NAME}
  ports:
    - port: 80
      nodePort: ${K8S_SERVICE_PORT}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ${APPLICATION_NAME}
spec:
  ingressClassName: jtektrnd-net
  rules:
    - host: ${APPLICATION_NAME}.jtektrnd.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ${APPLICATION_NAME}
                port:
                  number: 80
